name: Captchas
author: Yukun
main: me.yukun.captchas.Captchas
version: ${project.version}
api-version: 1.21
softdepend: [ AuthMe ]
description: >
  A plugin to force players to complete captchas when players do certain tasks.
commands:
  captchas:
    description: Base command for Captchas plugin.
    aliases: [ captcha, cpc ]