name: Captchas
author: Yukun
main: me.yukun.captchas.Main
version: 1.0.1d
api-version: 1.20
softdepend: [ AuthMe ]
description: >
  A plugin to force players to complete captchas when players do certain tasks.
commands:
  captchas:
    description: Base command for Captchas plugin.
    aliases: [ captcha, cpc ]